export const COUNTRIES: string[]=[
        "Ireland",
        "United Kingdom",
        "New Zealand",
        "Sri Lanka",
        "Alaska",
        "Hawai",
        "Marshall Islands",
        "Puerto Rico",
        "Russia",
        "Canada",
        "Belize",
        "Costa Rica",
        "Cuba",
        "Dominican Republic",
        "El Salvador",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Mexico",
        "Nicaragua",
        "Panama",
        "Bahamas",
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Ecuador",
        "Galapagos Islands",
        "French Guiana",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
        "Colombia",
        "Greenland",
        "Algeria",
        "Angola",
        "Botswana",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Congo",
        "Benin",
        "Equatorial Guinea",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Ivory Coast",
        "Liberia",
        "Libya",
        "Madagascar",
        "Mali",
        "Maurithania",
        "Mauritius",
        "Morocco",
        "Niger",
        "Nigeria",
        "Guinea-Bissau",
        "Rwanda",
        "Sao Tome and Principe",
        "Senegal",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "Lesotho",
        "Zimbabwe",
        "Namibia",
        "Western Sahara",
        "Swaziland",
        "Togo",
        "Tunisia",
        "Egypt",
        "Burkina Faso",
        "Burundi",
        "DR Congo",
        "Uganda",
        "Malawi",
        "Mozambique",
        "Tanzania",
        "Zambia",
        "Austria",
        "Belgium",
        "Cyprus",
        "Czech Republic",
        "Hungary",
        "Denmark",
        "Germany",
        "Poland",
        "Greece",
        "Turkey",
        "Iceland",
        "Italy",
        "Luxembourg",
        "Netherlands",
        "Portugal",
        "Romania",
        "Slovenia",
        "Croatia",
        "Bosnia and Herzegovina",
        "Serbia",
        "Montenegro",
        "Spain",
        "Norway",
        "Sweden",
        "Switzerland",
        "Comoros",
        "Mayotte",
        "New Caledonia",
        "Reunion",
        "French Southern and Atlantic Lands",
        "France",
        "Afghanistan",
        "Bahrain",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Oman",
        "Dubai",
        "Pakistan",
        "Quatar",
        "Saudi Arabia",
        "Syria",
        "United Arab Emirates",
        "Yemen",
        "Iran",
        "Finland",
        "Isle of Man",
        "Australia",
        "Solomon Islands",
        "Brunei",
        "Papua New Guinea",
        "polygon5199",
        "Phillipines",
        "Indonesia",
        "Fiji",
        "Vanuatu",
        "Bangladesh",
        "Bhutan",
        "Myanmar",
        "Cambodia",
        "China",
        "Hainan",
        "Taiwan",
        "North Korea",
        "South Korea",
        "Laos",
        "Malaysia",
        "Nepal",
        "Singapore",
        "Thailand",
        "Vietnam",
        "India",
        "Mongolia",
        "Estonia",
        "Latvia",
        "Lithuania",
        "Belarus",
        "Moldova",
        "Ukraine",
        "Armenia",
        "Azerbaijan",
        "Georgia",
        "Turkmenistan",
        "Uzbekistan",
        "Kazakhstan",
        "Kyrgyzstan",
        "Tajikistan",
        "Albania",
        "Macedonia",
        "Bulgaria",
        "Hong Kong",
        "Bermuda",
        "Cayman Islands",
        "Gibraltar",
        "Jersey",
        "Slovakia",
        "Kosovo",
        "Kenya",
        "Japan",
        "Virgin Islands",
        "British Virgin Islands",
        "Trinidad and Tobago",
        "Aruba",
        "Grenada",
        "St. Vincent and the Grenadines",
        "Barbados",
        "Guadeloupe",
        "Martinique",
        "St. Lucia",
        "Dominicana",
        "Anigua and Barbuda",
        "St. Kitts and Nevis",
        "Anguilla",
        "Bonaire",
        "nl",
        "xs",
        "Curacao",
        "mf",
        "Montserrat",
        "Sudan",
        "South Sudan",
        "Andaman and Nicobar islands",
        "Seychelles",
        "Malta",
        "Liechtenstein",
        "East Timor",
        "South Dakota",
        "Nebraska",
        "Wyoming",
        "Colorado",
        "Kansas",
        "iowa",
        "Utah",
        "Minnesota",
        "Oklahoma",
        "New Mexico",
        "Arizona",
        "California",
        "Nevada",
        "Oregon",
        "Montana",
        "Washington",
        "Idaho",
        "North Dakota",
        "Wisconsin",
        "Illinois",
        "Michigan",
        "Indiana",
        "Ohio",
        "Missouri",
        "Arkansas",
        "Louisiana",
        "Mississippi",
        "Alabama",
        "Georgia (US)",
        "Tennessee",
        "Kentucky",
        "Virginia",
        "North Carolina",
        "South Carolina",
        "Pennsylvania",
        "New York",
        "New Jersey",
        "Delaware",
        "Maryland",
        "West Virginia",
        "Connecticut",
        "Vermont",
        "New Hampshire",
        "Maine",
        "Massachusetts",
        "Rhode Island",
        "Florida",
        "Texas",
        "Washington DC",
      ]